### ISSUE TITLE
Support integrating mybatis-dynamic-sql

### ISSUE THREAD

**Issue by kazuki43zoo** [kazuki43zoo/mybatis-spring-native#11]
Support integrating https://github.com/mybatis/mybatis-dynamic-sql

**Comment by kazuki43zoo** [comment]
@jeffgbutler

I try to add the integration feature for `mybatis-dynamic-sql` use on `spring-native`. I want to know to classes that access using reflection feature. Are there any classes that access using reflection other than following classes?

https://github.com/kazuki43zoo/mybatis-spring-native/blob/master/mybatis-spring-native-extensions/src/main/java/org/mybatis/spring/nativex/MyBatisDynamicSqlNativeConfiguration.java#L49-L58

**Comment by jeffgbutler** [comment]
@kazuki43zoo I don't know much about Java native so I'm not sure what could cause trouble. But there is no direct usage of reflection except in the `SqlProviderAdapter`.

Does unchecked casting cause issues? There are several unchecked casts in the library.

**Comment by kazuki43zoo** [comment]
@jeffgbutler 
When use reflection in Java Native(Graal VM), we need to mark class that access by reflection using [configuration file](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/). Therefore, I want to mark it, if there is matches class in library. If there is not mark, cannot found class or member at runtime.

> Does unchecked casting cause issues?

Probably, no problem.

**Comment by kazuki43zoo** [comment]
I've closed this issue.
